postgres:
  host: "localhost"
  port: 5432
  user: "dhanush"
  password: "dkarcher"
  database: "forensics"

mongodb:
  uri: "mongodb://localhost:27017/"
  database: "forensics"

neo4j:
  user: "neo4j"
  password: "password"

milvus:
  host: "127.0.0.1"
  port: "19530"
